### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by hexicle** [hexicle/penpal#1]
- [x] Switch to API.AI and Firebase
- [ ] Actually connect users to each other
- [ ] Prepare a home website for the project.
